### ISSUE TITLE
Json Parse Crash

### ISSUE THREAD

**Issue by floation-cutie** [Ghabriel/PokemonCpp#2]
When I try to execute the pokemon binary file,
I ran into this problem, I don't know what's wrong with your resource
```
pokemon: include/engine/resource-system/json/parse-json.hpp:47: JsonValue __detail::parseJSON(JsonScanner&, const Token&): Assertion `false' failed.
Aborted
```

**Comment by Ghabriel** [comment]
Hey @floation-cutie! I haven't worked on this in a very long time (5+ years) but my guess would be that one of the dependencies on your machine is in a version that's too recent. I've just tested it locally with SFML 2.5, Lua 5.3, and GCC 9.4 and it worked fine.

Also keep in mind that this project is wildly incomplete as I stopped working on it soon after I got the basic systems working, so it's nowhere close to a complete game.

**Comment by floation-cutie** [comment]
Hi,I reconstructed the environment again.
Now the original problem gone.
```cpp
[RESOURCE] Fonts: OK
[RESOURCE] Textures: OK
[RESOURCE] Animations: OK
[RESOURCE] Sound Effects: OK
[RESOURCE] BGM: OK
[RESOURCE] TILES: OK
[RESOURCE] Script 'map-1': OK
[RESOURCE] Maps: OK
[RESOURCE] Encounters: OK
[RESOURCE] Pokemon: OK
[RESOURCE] Pokemon sprites: OK
[RESOURCE] Moves: OK
[RESOURCE] Script 'ai': OK
[RESOURCE] Script 'moves': OK
[RESOURCE] Battle scripts: OK
Setting vertical sync not supported
```
And this poped out, could you tell me what's wrong?
Sorry from a rookie
```cpp
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  148 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  111
  Current serial number in output stream:  111
```

I‘m running on the windows WSL

**Comment by Ghabriel** [comment]
Are you on Windows 10? If so you have to configure an X Server before trying to run the game (or anything else that has a GUI via WSL). If you're on Windows 11 it should have one by default and then it'd work out of the box. Otherwise I'm not sure what the problem may be, this is a WSL issue and not really related to the game so there's not much I can do here to help.

**Comment by floation-cutie** [comment]
Well then, can you send me a video of what the game demo looks like or something, please?
I think your project has very clear structure, and should be worth learning,thanks.

**Comment by Ghabriel** [comment]
Here's a video showing what the demo looks like:

https://github.com/Ghabriel/PokemonCpp/assets/461966/65032928-c93b-4fbd-8c7d-8c3db428a70a
